language: ruby
rvm:
 - 2.2
notifications:
  email: false
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database flashcards_test;' -U postgres
  - cp config/secrets.yml.travis config/secrets.yml
  - cp config/application.yml.travis config/application.yml
