language: ruby
rvm:
 - 2.2
notifications:
  email: false
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database flashcards_test;' -U postgres
  - cp .env.travis .env
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - bundle exec rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
